In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
SIZE = 200
image = np.zeros((SIZE,SIZE), dtype=int)
print(image)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
